# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8df2dcf983ac8a373a25d70bd5759a6096af18bd976f77857a58e5e1f7e18fac750cb5ddb9a554e090d5b3ef8b940c6982532a80d42f7e92847992c66e484a3

test:
  secret_key_base: f9e389b91b2e497778e3e33cc9ea1a12158b220534e56dadcb495445b3342b4dda23ee17059ebe542c27a5575aeeb85fa5f58c4bc64809009b350cbb9ecf2e58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
